name: planningpoker
description: Projeto para fazermos Plannings

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  sqflite:
  path:
  cupertino_icons: ^1.0.2
  google_fonts: ^2.0.0
  flutter_svg: ^1.0.3
  fl_chart: ^0.50.1
  provider: ^6.0.2
  intl: ^0.17.0
  charts_flutter:
  polls: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  

flutter:
  uses-material-design: true

assets:
  - assets/images/
  